site_name: Bionic Blue lore
site_url: https://bionicbluelore.indiesmiths.com
nav:
    - Home: README.md
    - About: about.md
repo_url: https://github.com/IndieSmiths/bionicbluelore
edit_uri: blob/develop/docs/
theme:
    name: mkdocs
    color_mode: dark
    user_color_mode_toggle: true
markdown_extensions:
    - toc:
        permalink: "#"
